# Generated by Django 4.1.3 on 2023-01-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productColourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=500)),
                ('Colour', models.CharField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('BLACK', 'black')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=700)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Size', models.CharField(choices=[(10, 'TEN'), (20, 'TWENTY'), (30, 'THIRTY')], max_length=50)),
                ('Quality', models.CharField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('MEDIUM', 'medium')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='')),
                ('table1', models.ManyToManyField(to='projectapp.productmainmodel')),
                ('table2', models.ManyToManyField(to='projectapp.productcolourmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productcolourmodel',
            name='table1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.productmainmodel'),
        ),
    ]
